### ISSUE TITLE
Coudn't get the project to run

### ISSUE THREAD

**Issue by sabbirtkdr** [gpapp/ennuicastr-docker#1]
Hi, Thanks a lot for the dockerized version. Unfortunately, I am having a hard time running this dockerized version on my ubuntu server. I am not sure which values I should put on .env..
I dont want to do anythin fancy, just run and host it on my cloud server and access it through a public domain/ip.
Any help from your side will be very generous. Thanks a lot in advance, and keep up the good work!

**Comment by sabbirtkdr** [comment]
@gpapp  If I can run this project, I will be more than happy to offer my help in writing a good documentation on how to setup this script.

**Comment by gpapp** [comment]
Hello @tsabbir96 ,
I've abandoned this project over a year ago, as I could not overcome the connectivity issues listed in the README.MD. The jitsi application has probably improved since, and it may be possible to configure and fix the connection issues to the backing servers.
I'm glad if the source is useful for you to get started on this. Feel free to submit a pull request, and I'll merge it, if you managed to get it running!

**Comment by sabbirtkdr** [comment]
Hi @gpapp 
Great, could you tell me which env variables I should populate in the .env file? So that I can test the connectivity issues that you mentioned..

**Comment by gpapp** [comment]
Follow the instructions in the readme. Take the..env.template and fill it up until the line that t says you don't need to change anything below. There are several components to ennuicastr and jitsi, that need to interconnect. 
I was close setting my own up, but failed after a few months. I have extensive networking, development and architecture background, but could not figure out how to run it then
I don't know what changed in these projects since, and have no time for this, so you'd have to figure out on your own.
